
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbdflfdklfsdxvkvejwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZGZsZmRrbGZzZHh2a3ZlandyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDA3NTIsImV4cCI6MjA2MTYxNjc1Mn0.O5fdpBX05N-T454FFmwoW46s_aXO8Br-EQ1ZPzCa3Qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'habal-hub-auth',
    storage: localStorage
  },
  db: {
    schema: 'public',
  }
});
