// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laqqxaycpnpvupecfzgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhcXF4YXljcG5wdnVwZWNmemd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDQwNzYsImV4cCI6MjA1OTg4MDA3Nn0.hF6AgAcj5L8PZyFkDVMChN-dJD0Qv3islTZT2izhyMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);